name: 🐛 Plugin issue
description: File a bug report
title: "bug: "
labels: "type/bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for your problem.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: "Tell us what you see!"
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: markdown
    attributes:
      value: "## System"

  - type: input
    attributes:
      label: OS
      description: On which system do you run the app?
      placeholder: "Fedora Linux 36 (Workstation Edition)"
    validations:
      required: true
      
  - type: input
    attributes:
      label: DE/WM version
      description: Which version of desktop environment / window manager do you use?
      placeholder: "GNOME 42.3, i3wm 4.21"
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: Which version of the Gradience do you use?
      placeholder: "0.3.0, 0.3.0-7e0386b, `main` branch"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Installation method
      description: How did you install Gradience ?
      options:
        - Flatpak from Flathub
        - Flatpak from Github Actions
        - Flatpak from manual build
        - AUR
        - Fedora COPR (lyessaadi/gradience)
        - Manual using meson
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Enabled system extensions (GNOME specific)
      description: "Please paste here a list of enabled extensions, unless you know that this information won't be needed in your issue."
      placeholder: "Use `gnome-extensions list --enabled` command to get a list."

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
