name: "💡 Plugin request"
description: Suggest a plugin"
title: "plugin: "
labels: ["enhancement", "plugin-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute! Contributions are what make the open-source and the GNOME community such an amazing place to learn, and create. Any contributions you make will benefit everybody else and are greatly appreciated.
  - type: textarea
    id: description
    attributes:
      label: Plugin description
      description: A clear and concise description of what the feature request is. Please include if your feature request is related to a problem and the links to the related project if applicable 
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: "List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to add, use case, Stack Overflow links, forum links, screenshots, OS if applicable, etc."
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Did you read the Code of Conduct?
      options:
        - label: I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).
          required: true
